Updated to carbon-kernel 5.2.0-m3 and carbon-feature-plugin 3.0.0
wso2/carbon-jndi pull request #33
Opened 2017-02-15 06:11 UTC by ashensw

This is regarding the kernel update requested for IS 6.0.0-m3 [1].
[1] [IS-6.0] Updating carbon-kernel version to 5.2.0-m3

2017-02-16 04:58 UTC, ChanakaCooray commented on tests/test-distribution/pom.xml
> +  ~ Copyright 2016 WSO2, Inc. (http://wso2.com)
Can you update the LICENSE?

2017-02-16 04:59 UTC, ChanakaCooray requested changes

2017-02-16 04:59 UTC, ChanakaCooray commented on tests/test-distribution/pom.xml
> +  ~ Copyright 2016 WSO2, Inc. (http://wso2.com)
Can you update the LICENSE?

2017-02-16 04:59 UTC, ChanakaCooray commented on tests/test-distribution/src/assembly/bin.xml
> + Copyright (c) 2016, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
Can you update the LICENSE?

2017-02-16 05:10 UTC, ashensw commented on tests/test-distribution/pom.xml
> +  ~ Copyright 2016 WSO2, Inc. (http://wso2.com)
done.

2017-02-16 05:11 UTC, ashensw commented on tests/test-distribution/src/assembly/bin.xml
> + Copyright (c) 2016, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
done.

2017-03-02 00:33 UTC, kasunbg approved these changes

2017-03-02 03:05 UTC, Niranjan-K requested changes

2017-03-02 03:05 UTC, Niranjan-K commented on tests/test-distribution/pom.xml
> +                <version>${carbon.feature.plugin.version}</version>
plugin version should be mentioned in the root pom

2017-03-02 03:38 UTC, ashensw commented on tests/test-distribution/pom.xml
> +                <version>${carbon.feature.plugin.version}</version>
removed it.

2017-03-02 05:30 UTC, ChanakaCooray approved these changes

2017-03-02 09:29 UTC, kasunbg commented on tests/test-distribution/pom.xml
> +                <version>${carbon.feature.plugin.version}</version>
Thanks ashen

2017-03-02 09:29 UTC, merged